server:
  port: ${SERVER_PORT}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: STUDENT
          uri: lb://STUDENT
          predicates:
            - Path=/student/**
        - id: SCHOOL-SERVICE
          uri: lb://SCHOOL
          predicates:
            - Path=/school/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
